-- ShipIt sentiment voting table (source of truth)
-- Run this once in Supabase SQL editor.

do $$
declare
    projects_id_type text;
    users_id_type text;
begin
    select pg_catalog.format_type(a.atttypid, a.atttypmod)
      into projects_id_type
    from pg_catalog.pg_attribute a
    join pg_catalog.pg_class c on c.oid = a.attrelid
    join pg_catalog.pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'projects'
      and a.attname = 'id'
      and a.attnum > 0
      and not a.attisdropped;

    select pg_catalog.format_type(a.atttypid, a.atttypmod)
      into users_id_type
    from pg_catalog.pg_attribute a
    join pg_catalog.pg_class c on c.oid = a.attrelid
    join pg_catalog.pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'users'
      and a.attname = 'id'
      and a.attnum > 0
      and not a.attisdropped;

    if projects_id_type is null then
        raise exception 'public.projects(id) not found';
    end if;

    if users_id_type is null then
        raise exception 'public.users(id) not found';
    end if;

    execute format(
        $sql$
        create table if not exists public.project_votes (
            id bigint generated by default as identity primary key,
            project_id %1$s not null references public.projects(id) on delete cascade,
            user_id %2$s not null references public.users(id) on delete cascade,
            sentiment text not null,
            created_at timestamptz not null default now(),
            updated_at timestamptz not null default now(),
            constraint project_votes_sentiment_check check (
                sentiment in (
                    'bullish',
                    'shipping',
                    'underrated',
                    'would_use',
                    'would_pay',
                    'promising',
                    'dead'
                )
            ),
            constraint project_votes_project_user_unique unique (project_id, user_id)
        );
        $sql$,
        projects_id_type,
        users_id_type
    );
end
$$;

create index if not exists project_votes_project_id_idx
    on public.project_votes (project_id);

create index if not exists project_votes_user_id_idx
    on public.project_votes (user_id);

create or replace function public.project_votes_set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

drop trigger if exists trg_project_votes_set_updated_at on public.project_votes;

create trigger trg_project_votes_set_updated_at
before update on public.project_votes
for each row
execute function public.project_votes_set_updated_at();
